promissions:
- guest
- student
- admin
deadlines:
- score: 1
network: 10.210.128.0/24

description: "description.pdf"

init: 
- exec: ["bash", "{{ .LABDIR }}/init.sh", "{{ .userip }}", "{{ .username }}"]
  timeout: 5
  worker:
    workertype: "Docker"
    workerpool: "main"

clear:
- exec: ["bash", "{{ .LABDIR }}/clear.sh", "{{ .userip }}", "{{ .username }}"]
  timeout: 5
  worker:
    workertype: "Docker"
    workerpool: "main"

checkpoints:
  Router:
  - message: Hostname and ip are set correctly.
    commands:
    - exec: ["bash", "{{ .LABDIR }}/Router/0.sh", "{{ .userip }}", "{{ .username }}"]
      timeout: 20
      worker:
        workertype: "Docker"
        workerpool: "main"
    weight: 10
  CLT:
  - message: Hostname and ip are set correctly.
    commands:
    - exec: ["bash", "{{ .LABDIR }}/CLT/0.sh", "{{ .userip }}", "{{ .username }}"]
      timeout: 20
      worker:
        workertype: "Docker"
        workerpool: "main"
    weight: 10
  - message: Can access the Internet normally through gw.
    commands:
    - exec: ["bash", "{{ .LABDIR }}/CLT/1.sh", "{{ .userip }}", "{{ .username }}"]
      timeout: 20
      worker:
        workertype: "Docker"
        workerpool: "main"
    weight: 20
    dependencies:
      CLT:
      - 0
  - message: Check whether the IP behind the NAT is an WAN IP.
    commands:
    - exec: ["bash", "{{ .LABDIR }}/CLT/2.sh", "{{ .userip }}", "{{ .username }}"]
      timeout: 20
      worker:
        workertype: "Docker"
        workerpool: "main"
    weight: 20
    dependencies:
      CLT:
      - 1
  Firewall:
  - message: Check if unnecessary traffic is blocked.
    commands:
    - exec: ["bash", "{{ .LABDIR }}/Firewall/0.sh", "{{ .userip }}", "{{ .username }}"]
      timeout: 60
      worker:
        workertype: "Docker"
        workerpool: "main"
    weight: 20
  - message: Check if the connection can access the Internet normally.
    commands:
    - exec: ["bash", "{{ .LABDIR }}/Firewall/1.sh", "{{ .userip }}", "{{ .username }}"]
      timeout: 20
      worker:
        workertype: "Docker"
        workerpool: "main"
    weight: 20
    dependencies:
      Firewall:
      - 0

contents: []
